
import React, { useState } from 'react';
import { Bot, ArrowRight, Send } from 'lucide-react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "@/hooks/use-toast";

const ProductDescriptionGenerator = () => {
  const [product, setProduct] = useState('');
  const [tone, setTone] = useState('professional');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState('');
  const [selectedPrompt, setSelectedPrompt] = useState('');
  
  const tones = [
    { value: 'professional', label: 'Professional' },
    { value: 'casual', label: 'Casual' },
    { value: 'enthusiastic', label: 'Enthusiastic' },
    { value: 'luxury', label: 'Luxury' },
    { value: 'technical', label: 'Technical' },
  ];
  
  const examplePrompts = [
    `Write a 50-word upbeat description for [${product || 'Product X'}] highlighting its durability.`,
    `Create a story-driven product description for [${product || 'Product X'}] that connects with eco-conscious customers.`,
    `Generate a concise, feature-focused description for [${product || 'Product X'}] emphasizing its unique selling points.`,
    `Craft a luxury-tone product description for [${product || 'Product X'}] that creates exclusivity and desirability.`,
  ];
  
  const handlePromptSelect = (prompt: string) => {
    setSelectedPrompt(prompt);
  };
  
  const handleSubmit = async () => {
    if (!product) {
      toast({
        title: "Product name required",
        description: "Please enter a product name before submitting",
        variant: "destructive",
      });
      return;
    }
    
    setLoading(true);
    
    try {
      // In a real implementation, this would call the Supabase function
      // const { data, error } = await supabase.functions.invoke('chat-message', {
      //   body: { prompt: selectedPrompt || `Write a ${tone} description for ${product}` }
      // });
      
      // if (error) throw error;
      
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1500));
      setResult(`This is a simulated ${tone} product description for ${product}. In a real implementation, this would be generated by an AI model based on the prompt: "${selectedPrompt || `Write a ${tone} description for ${product}`}"`);
      
      toast({
        title: "Description generated",
        description: "Your product description has been created successfully",
      });
    } catch (error) {
      toast({
        title: "Generation failed",
        description: "There was an error generating your product description",
        variant: "destructive",
      });
      console.error(error);
    } finally {
      setLoading(false);
    }
  };
  
  return (
    <div className="p-6 max-w-5xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-xl font-medium flex items-center">
          <Bot className="mr-2" size={20} />
          Product Description Generator
        </h2>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="neuro">
          <CardHeader>
            <CardTitle>Create Product Description</CardTitle>
            <CardDescription>
              Generate compelling product descriptions with AI assistance
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="product-name">Product Name</Label>
              <Input 
                id="product-name"
                placeholder="Enter product name" 
                value={product}
                onChange={(e) => setProduct(e.target.value)}
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="tone">Tone</Label>
              <Select value={tone} onValueChange={setTone}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select tone" />
                </SelectTrigger>
                <SelectContent>
                  {tones.map((tone) => (
                    <SelectItem key={tone.value} value={tone.value}>
                      {tone.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="custom-prompt">Custom Prompt</Label>
              <Textarea 
                id="custom-prompt"
                placeholder="Write a custom prompt or select from examples below"
                value={selectedPrompt}
                onChange={(e) => setSelectedPrompt(e.target.value)}
                className="min-h-[100px]"
              />
            </div>
          </CardContent>
          <CardFooter className="flex justify-between">
            <Button onClick={handleSubmit} disabled={loading}>
              {loading ? "Generating..." : "Generate Description"}
              {!loading && <Send className="ml-2" size={16} />}
            </Button>
          </CardFooter>
        </Card>
        
        <div className="space-y-6">
          <Card className="neuro">
            <CardHeader>
              <CardTitle>Example Prompts</CardTitle>
              <CardDescription>
                Select a template to get started quickly
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-2">
              {examplePrompts.map((prompt, index) => (
                <button
                  key={index}
                  className="neuro-sm neuro-hover neuro-active p-3 rounded-lg flex items-center justify-between w-full text-left"
                  onClick={() => handlePromptSelect(prompt)}
                >
                  <div className="text-sm truncate">{prompt}</div>
                  <ArrowRight size={14} className="opacity-50 shrink-0" />
                </button>
              ))}
            </CardContent>
          </Card>
          
          {result && (
            <Card className="neuro">
              <CardHeader>
                <CardTitle>Generated Description</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="p-4 bg-neuro-dark rounded-lg text-sm">
                  {result}
                </div>
              </CardContent>
              <CardFooter className="flex justify-between">
                <Button variant="outline" onClick={() => navigator.clipboard.writeText(result)}>
                  Copy to Clipboard
                </Button>
                <Button variant="outline" onClick={() => setResult('')}>
                  Clear
                </Button>
              </CardFooter>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
};

export default ProductDescriptionGenerator;
